// Category-specific automatic thumbnails, ported from the legacy builder's lib/thumbnailOptions:
// some categories are rendered offscreen in a fixed pose instead of screenshotting the preview.
import { WearableCategory } from '@dcl/schemas'
import poseNicerIdle from '~/assets/poses/pose_nicer_idle.glb?url'

export const THUMBNAIL_POSE_BY_CATEGORY: Partial<Record<WearableCategory, string>> = {
  [WearableCategory.UPPER_BODY]: poseNicerIdle,
  [WearableCategory.SKIN]: poseNicerIdle
}

/** URL of the pose GLB the auto thumbnail uses for this category, or null for a plain screenshot. */
export function getThumbnailPose(category: string | null | undefined): string | null {
  return (category && THUMBNAIL_POSE_BY_CATEGORY[category as WearableCategory]) || null
}

export type AutoThumbnailInfo = {
  category: string | null
  /** True when the current thumbnail was generated by us (not zip-provided or user-picked). */
  isAutoThumbnail: boolean
  /** Category the auto thumbnail was rendered for. */
  autoThumbnailCategory: string | null
}

/** True when the auto thumbnail was rendered for a category whose pose differs from the current one. */
export function isAutoThumbnailStale(draft: AutoThumbnailInfo): boolean {
  return draft.isAutoThumbnail && getThumbnailPose(draft.category) !== getThumbnailPose(draft.autoThumbnailCategory)
}
